# 照片分類工具設定檔

# 原始照片資料夾路徑
src_dir: "."

# 整理後儲存的位置
dst_dir: "."

# 最大併發處理數量
workers: 4

# 是否為乾跑模式（只顯示將要移動的檔案，不實際執行）
dry_run: false

# 要忽略的檔案類型
ignore:
  - ".git"
  - ".gitignore"
  - ".go"
  - ".mod"
  - ".sum"
  - ".md"
  - ".log"
  - ".yaml"
  - ".sample" 
