// Code generated by MockGen. DO NOT EDIT.
// Source: photo-sorter/internal/pkg/metadata (interfaces: ExifReader)

// Package metadata is a generated GoMock package.
package metadata

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockExifReader is a mock of ExifReader interface.
type MockExifReader struct {
	ctrl     *gomock.Controller
	recorder *MockExifReaderMockRecorder
}

// MockExifReaderMockRecorder is the mock recorder for MockExifReader.
type MockExifReaderMockRecorder struct {
	mock *MockExifReader
}

// NewMockExifReader creates a new mock instance.
func NewMockExifReader(ctrl *gomock.Controller) *MockExifReader {
	mock := &MockExifReader{ctrl: ctrl}
	mock.recorder = &MockExifReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExifReader) EXPECT() *MockExifReaderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockExifReader) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockExifReaderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockExifReader)(nil).Close))
}

// GetExifData mocks base method.
func (m *MockExifReader) GetExifData(arg0 string) (*ExifData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExifData", arg0)
	ret0, _ := ret[0].(*ExifData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExifData indicates an expected call of GetExifData.
func (mr *MockExifReaderMockRecorder) GetExifData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExifData", reflect.TypeOf((*MockExifReader)(nil).GetExifData), arg0)
}
