version: "0.1.11"  # 版本號

# 照片分類工具設定檔

# 原始照片資料夾路徑
src_dir: "source_media"

# 整理後儲存的位置
dst_dir: ""

# 是否為乾跑模式（只顯示將要移動的檔案，不實際執行）
dry_run: false

# 日期格式：YYYY-MM-DD (2006-01-02) 或 YYYY-MM (2006-01)
date_format: "2006-01"

# 是否啟用地理位置標籤
enable_geo_tag: true

# GeoJSON 檔案路徑
geo_json_path: "./geodata/states.geojson"

# 地理編碼器類型
geocoder_type: "geo_state"

# 日誌等級設定 (debug, info, warn, error)
log_level: "info"

# 是否啟用驗證
enable_verify: true

# 支援的檔案格式
formats:
  - ".jpg"
  - ".jpeg"
  - ".heic"
  - ".png"
  - ".mp4"
  - ".mov" 
  
# 要忽略的檔案類型
ignore:
  - ".git"
  - ".gitignore"
  - ".go"
  - ".mod"
  - ".sum"
  - ".md"
  - ".log"
  - ".yaml"
  - ".sample"
  - ".DS_Store"
  - "Thumbs.db"
